services:
  mysql:
    image: mysql:8.3
    command: mysqld --user=root
    env_file:
      - ./server/.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - '3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
  migrate:
    image: migrate/migrate
    volumes:
      - ./server/database/migrations:/migrations
    links:
      - mysql
    depends_on:
      mysql: 
        condition: service_healthy
    env_file:
      - ./server/.env
    command:
      [
        '-path',
        '/migrations',
        '-database',
        'mysql://${DATABASE_USER}:${DATABASE_PASS}@tcp(mysql:3306)/${DATABASE_NAME}?multiStatements=true',
        'up',
        '3',
      ]
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - RUN_MODE=production
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_BASE_URL=http://localhost:3000
    depends_on:
      - server
    ports:
      - '80:80'
